In [4]:
# Q1. Write a Numpy program to get the Numpy version.
import numpy as np
print(np.__version__)

1.24.1


In [14]:
# Q2. Write a NumPy program to test whether none of the elements of a given array are zero.
import numpy as np

# Example array
array1 = np.array([1, 2, 5, 4, 5])
array2 = np.array([0, 2, 3, 4, 5])

result1 = np.all(array1!=0)
result2 = np.all(array2!=0)


print("For array1:", result1)  # Should print True
print("For array2:", result2)  # Should print False
    



For array1: True
For array2: False


In [2]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
import numpy as np
array1 = np.array([2,4,3,5,6])
array2 = np.array([2,4,7,8,6])



greater_than = array1 > array2
greater_than_equal = array1 >= array2
less_than = array1 < array2
less_than_equal = array1 <= array2


print("Array1:", array1)
print("Array2:", array2)
print("Array1 > Array2:", greater_than)
print("Array1 >= Array2:", greater_than_equal)
print("Array1 < Array2:", less_than)
print("Array1 <= Array2:", less_than_equal)



Array1: [2 4 3 5 6]
Array2: [2 4 7 8 6]
Array1 > Array2: [False False False False False]
Array1 >= Array2: [ True  True False False  True]
Array1 < Array2: [False False  True  True False]
Array1 <= Array2: [ True  True  True  True  True]


In [4]:
# Q4. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
import numpy as np

my_array = np.array([1,7,13,105])

# Determine the size of memory occupied by the array
memory_size_bytes = my_array.nbytes

# Convert bytes to human-readable format
if memory_size_bytes < 1024:
    memory_size_readable = f"{memory_size_bytes} B"
elif memory_size_bytes < 1024**2:
    memory_size_readable = f"{memory_size_bytes / 1024:.1f} KB"
elif memory_size_bytes < 1024**3:
    memory_size_readable = f"{memory_size_bytes / (1024**2):.1f} MB"
else:
    memory_size_readable = f"{memory_size_bytes / (1024**3):.1f} GB"

print("Array:", my_array)
print("Memory Occupied:", memory_size_readable)


Array: [  1   7  13 105]
Memory Occupied: 16 B


In [9]:
# Q5. Write a NumPy program to create an array of integers from 30 to 70.
import numpy as np
array = np.arange(30,71)
print("Array of integer from 30 to 70 is \n", array)

Array of integer from 30 to 70 is 
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [13]:
# Q6. Write a NumPy program to create an array of all even integers from 30 to 70.
import numpy as np
array = np.arange(30,71,2)
print("Array from 30 to 70 of all even is \n",array)

Array from 30 to 70 of all even is 
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
# Q7.  Write a NumPy program to create a 3x3 identity matrix.
import numpy as np

identity_matrix = np.eye(3)

print("3x3 Identity Matrix:\n",  identity_matrix)




3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Q8.Write a search NumPy program to create a 3X4 array and iterate over it.
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
    print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 