In [3]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print("Afterslicing")
print(a[1:])

print("\nAyush Suryavanshi")
print("Enrollment No.- 0108io211014")

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Afterslicing
[[3 4 5]
 [4 5 6]]

Ayush Suryavanshi
Enrollment No.- 0108io211014
